<?php
include ("header.php");
?>

<section id="main">
	<h2>Phones</h2><br>
	<div id="device-selector">
		<!-- device-selector generated by js -->

		<input type="checkbox" id="Apple" name="deviceSelector" value="Apple">
  		<label for="Apple"> Apple </label><br>
  		<input type="checkbox" id="Samsung" name="deviceSelector" value="Samsung">
  		<label for="Samsung"> Samsung </label><br>
  		<input type="checkbox" id="Google" name="deviceSelector" value="Google">
  		<label for="Google"> Google </label><br>

	</div>
	<div id="products" class="row">
		<!-- product-card generated by js -->
	</div> 
</section>
</div>
<script src="./js/readxml.js"></script>
<script src="./js/updateproduct.js"></script>

<?php
include ("footer.php");
?>
